### ISSUE TITLE
Defense Trainer does not consider recently discarded tiles as genbutsu

### ISSUE THREAD

**Issue by FabulousCupcake** [Euophrys/Riichi-Trainer#23]
**Steps to reproduce:**
After the first turn in the defense trainer, discard a tile that was discarded in the last turn, e.g.:

**State:**
<img width="1140" alt="Screen Shot 2019-08-02 at 16 53 40" src="https://user-images.githubusercontent.com/25855364/62379267-e7a1f580-b546-11e9-9b1c-300e4f767cd6.png">

**Action:** Discard 8s

**Expected:** 8s has safety rating of 15 (genbutsu).

**Actual:** Safety rating of 8s is not 15.
<img width="1147" alt="Screen Shot 2019-08-02 at 16 55 04" src="https://user-images.githubusercontent.com/25855364/62379342-0dc79580-b547-11e9-94e8-42279f4c14e5.png">

**Comment by Euophrys** [comment]
Well, that was an annoying dive into Javascript's weird handling of arrays containing one item, but it's fixed.
